tabWidth: 3
useTabs: true
semi: true
singleQuote: true
trailingComma: "es5"
bracketSpacing: true
bracketSameLine: true
parser: "typescript"
endOfLine: "lf"
singleAttributePerLine: false
proseWrap: "preserve"
