name: Build & Release

on:
  pull_request:
    types: [closed]
    branches: [ "master" ]


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
          - platform: 'windows-latest'
          
    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: check out git repo
      uses: actions/checkout@master

    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        
    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: lts/*

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
        targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: install js dependencies
      run: |
        corepack enable
        yarn install

    - uses: tauri-apps/tauri-action@v0
      env:
        PUBLISH_FOR_PULL_REQUEST: true
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
        releaseName: 'Factor v__VERSION__'
        releaseBody: 'See the assets to download this version and install.'
        releaseDraft: true
        prerelease: false
        args: ${{ matrix.args }}


