name: Build & Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: ['20.16.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: check out git repo
      uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}

    - name: install dependencies
      run: |
        corepack enable
        yarn install
        yarn run electron-builder install-app-deps

    - name: check types
      run: yarn run typecheck

    - name: bundle
      run: yarn run electron-vite build

    - name: build electron app
	 	env:
			GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: yarn run electron-builder

   # - name: release
   #   uses: softprops/action-gh-release@v2
   #   if: startsWith(github.ref, 'refs/tags/')
   #   with:
   #   files: ./dist/factor-v[0-9].[0-9][?0-9].[0-9][?0-9].*(app|exe|dmg|deb)
   #   token: ${{ secrets.PUB_TOKEN }}

