name: Build & Release

on:
  pull_request:
    types: [closed]
    branches: [ "master" ]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: ['lts']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: check out git repo
      uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}

	 - name: Setup Rust
	   uses: dtolnay/rust-toolchain@stable

	 - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: install js dependencies
      run: |
        corepack enable
        yarn install

	 - name: install rust dependencies
      run: |
        cd src-tauri
        cargo update


	 - uses: tauri-apps/tauri-action@v0
		env:
		   PUBLISH_FOR_PULL_REQUEST: true
			GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
		with:
			tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
			releaseName: 'App v__VERSION__'
			releaseBody: 'See the assets to download this version and install.'
			releaseDraft: true
			prerelease: false
			args: ${{ matrix.args }}


